### ISSUE TITLE
Delayed release example typo

### ISSUE THREAD

**Issue by RaphaelChristienECTL** [r-simmer/simmer.bricks#15]
In simmer bricks example on delayed release we have :
t <- trajectory() %>%
  seize("res1") %>%
  log_("res1 seized") %>%
  seize("res2") %>%
  log_("res2 seized") %>%
  delayed_release("res1", 2) %>% 
  log_("res1 released") %>%
  delayed_release("res2", 5, preemptive=TRUE) %>%
  log_("res1 released")

I suppose the last line should be log_("res2 released")  instead.

Cheers,

**Comment by Enchufa2** [comment]
Indeed, thanks!
