### ISSUE TITLE
delayed_release doesn't accept callable function for amount

### ISSUE THREAD

**Issue by whipson** [r-simmer/simmer.bricks#16]
The documentation for `simmer.bricks::delayed_release` states that the `amount` argument accepts "...either a numeric or a callable object (a function) which must return a numeric."

The latter part of this statement doesn't appear to true. Entering a callable function for amount results in an error:
```
simmer::trajectory() %>%
  simmer.bricks::delayed_release("res", task = 1, amount = function(x) 1)

Error in -amount : invalid argument to unary operator
```

**Comment by Enchufa2** [comment]
Thanks, fixed in master.
